<?php

/**
 * @file
 * Contains drush_utility.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drush_utility_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drush_utility module.
    case 'help.page.drush_utility':
      $output = '';
      $output .= '<h3>' . t('About Drush Utility') . '</h3>';
      $output .= '<p>' . t('Utility for dustom drush commands') . '</p>';
      $output .= '<p>' . t('It is for updating external links in body with the attributes no-follow i.e
      rel="nofollow"') . '</p>';
      $output .= '<p>' . t('Ex. drush extl-nf --all article') . '</p>';
      return $output;

    default:
  }
}
